[package]
name = "thread_pool"
version = "0.1.0"
authors = ["plutolove <sa517255@mail.ustc.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7.1"
crossbeam-utils = "0.6.5"
